/* Auto-generated by hw/generate_c.py -- do not edit by hand.
 * Flagship sepsis model (346 trees, 40 features) compiled to float C
 * for the Cortex-M4F on the Silicon Labs BRD2605A (SiWG917). Uses the hardware FPU. */
#ifndef SEPSIS_FLAGSHIP_MODEL_H
#define SEPSIS_FLAGSHIP_MODEL_H

#define SEPSIS_N_FEATURES 40
#define SEPSIS_N_TREES     346
#define SEPSIS_N_NODES     20414

/* Returns the raw margin (log-odds). */
float sepsis_predict_margin(const float x[SEPSIS_N_FEATURES]);
/* Returns calibrated-free sigmoid(margin) probability in [0,1]. */
float sepsis_predict_proba(const float x[SEPSIS_N_FEATURES]);

#endif /* SEPSIS_FLAGSHIP_MODEL_H */
