@echo off
REM Run the bit-exact co-simulation in Vivado XSim.
REM Usage: open the "Vivado Command Prompt" (or add Vivado\bin to PATH), then from the
REM project ROOT (d:\Sepsis Predictor) run:  hw\run_xsim.bat
REM Requires hw\golden_vectors.csv (generated by hw\generate_verilog.py).

echo === Compiling ===
call xvlog hw\sepsis_engine.v hw\tb_sepsis_engine.v
if errorlevel 1 goto :err

echo === Elaborating ===
call xelab tb_sepsis_engine -s tb_sim -debug typical
if errorlevel 1 goto :err

echo === Simulating (co-sim vs Python golden vectors) ===
call xsim tb_sim -runall
if errorlevel 1 goto :err

echo.
echo Done. For the waveform visualization:
echo   xsim tb_sim -gui    (then add waves, or open hw\tb_sepsis_engine.vcd)
goto :eof

:err
echo BUILD/SIM FAILED -- check messages above.
exit /b 1
